FROM armhf/alpine:3.5
MAINTAINER evanlezar@gmail.com

RUN apk update \
 && apk upgrade \
 && apk add --no-cache \
    py-pip \

 && pip install --upgrade pip \
 && pip install --upgrade speedtest-cli \

 && rm -rf /var/cache/apk/* \
 && rm -rf /tmp/* /var/tmp/*

CMD ["speedtest", "--json"]
